.TH scplugin-slepos "5" "15 Jul 2010" "scplugin-slepos" "Support Utilities Manual"
.SH NAME
scplugin-slepos \- SUSE Linux Enterprise Point of Sale Plugin for 
.BR supportconfig (1)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. Plugins are any script or executable that is placed in the /opt/supportconfig/plugins directory. Supportconfig uses this directory by default. All plugins need the execute permission and must send their output to stdout and stderr.

Plugins Included: amanda, clamav, dlu_pgina, groupwise, helpdesk, hylafax, mailscanner, openvpn, sentinel, simba.

All plugins must return a value 0 for successful completion, 111 for skipped, and any other non-zero error value. The return code of 111 is reserved for telling supportconfig the plugin is not installed and should be skipped.
.SH FILES
.I /opt/supportconfig/plugins
.RS
This is the default plugin directory. Copy all additional plugins to this directory.
.RE
.SH AUTHOR
Jason Record <jrecord@novell.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://en.opensuse.org/SC-Plugins#Reporting_Bugs
.SH SEE ALSO
.BR supportconfig (1)
.BR supportconfig.conf (5)
