#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for SLEPOS
# Description: Gathers important troubleshooting information
#              about SUSE Linux Enterprise Point of Service
# License:     GPLv2
# Author:      Jason Record (jrecord@novell.com)
#              Thomas Schlosser (schloss@suse.de)
# Modified:    2010 Oct 21
#############################################################

SVER=1.0.4
LOG_LINES=0	#0 means include the entire file
unset FILES
RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"

[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }

section_header "Supportconfig Plugin for SLEPOS, v${SVER}"
pconf_files /etc/slepos-release


# Generic
section_header "SLEPOS: Generic"
	test -d /etc/SLEPOS/ && FILES=$(find /etc/SLEPOS/ -type f| grep -v "/etc/SLEPOS/template/" | grep -v "/etc/SLEPOS/installation.xml" | grep -v "/etc/SLEPOS/adminserver.conf"| grep -v "/etc/SLEPOS/branchserver.conf") || unset FILES
	pconf_files $FILES



# Adminserver
section_header "SLEPOS: Admin Server"
if rpm -q POS_Server-Admin3 &>/dev/null; then
        test -d /srv/SLEPOS/ && \
	for DIR in $(find . /srv/SLEPOS/ -maxdepth 1| grep -v "\." ); do plugin_command "ls -la $DIR"; done

	if test -f /etc/SLEPOS/adminserver.conf; then
		plugin_command "sed /etc/SLEPOS/adminserver.conf -e '/^[[:space:]]*#/d' -e '/^$/d' -e 's/POS_ADMIN_PASSWORD.*/POS_ADMIN_PASSWORD=REMOVED/g'" 
	else
		plugin_message "#==[ Configuration File ]===========================#"
		plugin_message "# /etc/SLEPOS/adminserver.conf - File not found"
		plugin_message
	fi

	plugin_command "slapcat -d 0 | sed -e 's/userPassword::.*/userPassword:: REMOVED/g'"
else
	plugin_message "# Not Installed"
	plugin_message
fi



# Branchserver
section_header "SLEPOS: Branch Server"
if rpm -q POS_Server-BranchTools3 &>/dev/null; then 

	test -d /srv/tftpboot/ && \
	for DIR in $(find . /srv/tftpboot/ -maxdepth 1| grep -v "\." ); do plugin_command "ls -la $DIR"; done

	if test -f /etc/SLEPOS/branchserver.conf; then
		plugin_command "sed /etc/SLEPOS/branchserver.conf -e '/^[[:space:]]*#/d' -e '/^$/d' -e 's/POS_ADMIN_PASSWORD.*/POS_ADMIN_PASSWORD=REMOVED/g;s/LEASES2LDAP_ADMIN_PW.*/LEASES2LDAP_ADMIN_PW=REMOVED/g' " 
	else
		plugin_message "#==[ Configuration File ]===========================#"
		plugin_message "# /etc/SLEPOS/branchserver.conf - File not found"
		plugin_message
	fi

	test -d /srv/tftpboot/CR/ && FILES=$(find /srv/tftpboot/CR/ -type f | grep -v ".tar" ) || unset FILES
	pconf_files $FILES
	
	test -d /srv/tftpbot/upload/ && FILES=$(find /srv/tftpboot/upload/ -type f | grep hwtype ) || unset FILES
	pconf_files $FILES /srv/tftpboot/boot/pxelinux.cfg /var/lib/dhcp/db/dhcpd.leases
else
	plugin_message "# Not Installed"
	plugin_message
fi

# Imageserver
section_header "SLEPOS: Image Server"
if rpm -q POS_Image3 &>/dev/null; then

        test -d /usr/share/kiwi/image/SLEPOS/ && \
	for DIR in $(find . /usr/share/kiwi/image/SLEPOS/ -maxdepth 0| grep -v "\." ); do plugin_command "ls -la $DIR"; done

	FILES=$(find /var/lib/SLEPOS/system/ -maxdepth 1 -type d | grep -v /var/lib/SLEPOS/system/chroot | grep -v /var/lib/SLEPOS/system/images | grep -v "system\/$") || unset FILES
	test -n "$FILES" && for DIR in $FILES; do plugin_command "ls -la $DIR"; done

	FILES=$(find /var/lib/SLEPOS/system/ -regex ".*/\(config\.sh\|config\.xml\|images\.sh\)") || unset FILES
	pconf_files $FILES

else
	plugin_message "# Not Installed"
	plugin_message
fi
section_header Done
